package com.gildedrose;

import org.approvaltests.combinations.CombinationApprovals;
import org.junit.jupiter.api.Test;

class GildedRoseTest {

    @Test
    void updateQualityMethod() {

        /**
         * testing all the combinations generated by all the if statements
         *  found by running the code with coverage, more info in the Readme.md
         */
        CombinationApprovals.verifyAllCombinations(this::newItemAndUpdateQuality,
                new String[]{"foo"},
                new Integer[]{0},
                new Integer[]{0});
    }

    private String newItemAndUpdateQuality(String itemName, int itemSellIn, int itemQuality) {
        Item[] items = new Item[] { new Item(itemName, itemSellIn, itemQuality) };
        GildedRose app = new GildedRose(items);
        app.updateQuality();
        return app.items[0].toString();
    }

}
